spring.application.name=lab1_s2
spring.datasource.url=jdbc:mysql://localhost:3306/co2124db
spring.datasource.username=root
spring.datasource.password=Chelseafc123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

spring.web.resources.static-locations=classpath:/static/
